### ISSUE TITLE
Request to add Iowa to ccdd-categories.md skeleton

### ISSUE THREAD

**Issue by aw-iowa** [CDCgov/Rnssp-rmd-templates#9]
Can you add Site "887 - Iowa" to the site parameter choices? Thank you. I manually added it locally, but I'm sure you want it in the skeleton.

**Comment by rosericazondekon** [comment]
Thank you @aw-iowa for opening a new issue. "Site 887 - Iowa" has been added to the site parameter choices in the `essence_ccdd` template. 

If you are using the template on the Rstudio Workbench instance on the Biosense platform, be aware that this update will not be available system-wide before 02/22/2022 (due to Federal Holiday observance). 

If you are using this template from your local Rstudio Desktop, please, feel free to update it  (`Rnssp::add_rmd_template("essence_ccdd")`).

For more, please, check the `essence_ccdd` template documentation at https://cdcgov.github.io/Rnssp-rmd-templates/templates/essenceccdd/.
